/** Requirement management contracts: project-scoped versioned requirements
 *  plus source document ingestion, AI module splitting, and AI review reports.
 *
 * Mirrors WHartTest business intent (document → split → review → approve → generate)
 * without copying its DSL, prompts, or specific copy.
 */

// ─── Core requirement state machine ────────────────────────────────────────

export type RequirementStatus = "draft" | "in-review" | "approved" | "rejected" | "archived";
export type RequirementTransitionAction =
  | "create"
  | "update"
  | "submit-review"
  | "approve"
  | "reject"
  | "archive"
  | "delete";

export interface RequirementVersionDto {
  id: string;
  requirementId: string;
  projectId: string;
  version: number;
  title: string;
  content: string;
  status: RequirementStatus;
  createdBy: string;
  reviewedAt?: string;
  approvedAt?: string;
  approvedBy?: string;
  rejectedAt?: string;
  rejectedBy?: string;
  archivedAt?: string;
  archivedBy?: string;
  createdAt: string;
}

export interface RequirementReviewEventDto {
  id: string;
  requirementId: string;
  projectId: string;
  fromStatus?: RequirementStatus;
  toStatus: RequirementStatus;
  action: RequirementTransitionAction;
  actorId: string;
  createdAt: string;
}

export interface RequirementDto {
  id: string;
  projectId: string;
  title: string;
  content: string;
  status: RequirementStatus;
  version: number;
  createdBy: string;
  reviewedBy?: string;
  approvedBy?: string;
  rejectedBy?: string;
  archivedBy?: string;
  createdAt: string;
  updatedAt: string;
  versions: RequirementVersionDto[];
  reviewEvents: RequirementReviewEventDto[];
}

export interface CreateRequirementRequest {
  title: string;
  content: string;
}

export type UpdateRequirementRequest = Partial<CreateRequirementRequest>;

// ─── Requirement documents (Phase 3 R2: document-first ingestion) ──────────

export type RequirementDocumentStatus =
  | "uploaded"
  | "processing"
  | "extracted"
  | "failed";

export type RequirementDocumentKind = "pdf" | "docx" | "txt" | "md" | "html";

export interface RequirementDocumentDto {
  id: string;
  projectId: string;
  filename: string;
  mimeType: string;
  sizeBytes: number;
  checksum: string;
  status: RequirementDocumentStatus;
  /** Set when status = "extracted". Not returned by list endpoint to keep payload small. */
  parsedText?: string;
  parseError?: string;
  uploadedBy: string;
  createdAt: string;
  updatedAt: string;
}

// ─── Requirement modules (AI split + user adjustment) ──────────────────────

export interface RequirementModuleDto {
  id: string;
  documentId: string;
  projectId: string;
  order: number;
  title: string;
  content: string;
  confidenceScore?: number;
  isAutoGenerated: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface UpdateRequirementModulesRequest {
  modules: Array<{
    title: string;
    content: string;
    order: number;
  }>;
}

/** LLM output for module splitting — no persistence; consumed by service. */
export interface RequirementModuleSplit {
  title: string;
  content: string;
  order: number;
  confidence: number;
}

// ─── AI review reports ─────────────────────────────────────────────────────

/** LLM output for review — no persistence; consumed by service. */
export interface RequirementReviewDimensionResult {
  clarityScore: number;
  completenessScore: number;
  testabilityScore: number;
  boundariesScore: number;
  overallScore: number;
  issues: RequirementReviewIssue[];
  improvements: string[];
}

/** Alias kept for clarity in the LLM service boundary. */
export type RequirementReviewResult = RequirementReviewDimensionResult;

export type RequirementReviewStatus =
  | "pending"
  | "running"
  | "completed"
  | "failed";

export type RequirementReviewSeverity = "high" | "medium" | "low";

export interface RequirementReviewIssue {
  severity: RequirementReviewSeverity;
  message: string;
  suggestion?: string;
}

export interface RequirementReviewReportDto {
  id: string;
  documentId: string;
  projectId: string;
  status: RequirementReviewStatus;
  overallScore?: number;
  clarityScore?: number;
  completenessScore?: number;
  testabilityScore?: number;
  boundariesScore?: number;
  issues?: RequirementReviewIssue[];
  improvements?: string[];
  modelUsed?: string;
  startedAt?: string;
  finishedAt?: string;
  failureReason?: string;
  createdBy: string;
  createdAt: string;
}

export interface StartReviewRequest {
  providerId?: string;
}
