import { BadRequestException, NotFoundException } from "@nestjs/common";
import { describe, expect, it, vi } from "vitest";
import { RequirementModulesService } from "../src/modules/requirements/requirement-modules.service";

function makeService(prisma: Record<string, unknown>, llmDraft: Record<string, unknown> = {}) {
  return new RequirementModulesService(
    prisma as never,
    { record: vi.fn() } as never,
    llmDraft as never,
  );
}

describe("requirement modules", () => {
  it("list returns modules in order", async () => {
    const rows = [
      { id: "mod-1", documentId: "doc-1", projectId: "p", order: 1, title: "A", content: "a", confidenceScore: 0.9, isAutoGenerated: true, createdAt: new Date(), updatedAt: new Date() },
      { id: "mod-2", documentId: "doc-1", projectId: "p", order: 2, title: "B", content: "b", confidenceScore: null, isAutoGenerated: false, createdAt: new Date(), updatedAt: new Date() },
    ];
    const svc = makeService({
      requirementDocument: { findFirst: vi.fn().mockResolvedValue({ id: "doc-1", parsedText: "x", status: "extracted" }) },
      requirementModule: { findMany: vi.fn().mockResolvedValue(rows) },
    });
    const result = await svc.list("p", "doc-1");
    expect(result).toHaveLength(2);
    expect(result[0]!.confidenceScore).toBe(0.9);
    expect(result[1]!.confidenceScore).toBeUndefined();
  });

  it("autoSplit rejects when document not extracted", async () => {
    const svc = makeService({
      requirementDocument: { findFirst: vi.fn().mockResolvedValue({ id: "doc-1", parsedText: null, status: "uploaded" }) },
    });
    await expect(svc.autoSplit("p", "doc-1", "u")).rejects.toBeInstanceOf(BadRequestException);
  });

  it("autoSplit replaces existing modules with LLM output", async () => {
    const tx = {
      requirementModule: {
        deleteMany: vi.fn(),
        createMany: vi.fn(),
        findMany: vi.fn().mockResolvedValue([
          { id: "mod-1", documentId: "doc-1", projectId: "p", order: 1, title: "Auth", content: "Login", confidenceScore: 0.85, isAutoGenerated: true, createdAt: new Date(), updatedAt: new Date() },
        ]),
      },
    };
    const svc = makeService(
      {
        requirementDocument: { findFirst: vi.fn().mockResolvedValue({ id: "doc-1", projectId: "p", parsedText: "Login", status: "extracted", mimeType: "text/markdown" }) },
        $transaction: (cb: (tx: typeof tx) => unknown) => cb(tx),
      },
      {
        generateModules: vi.fn().mockResolvedValue({
          modules: [{ title: "Auth", content: "Login", order: 1, confidence: 0.85 }],
          modelUsed: "stub-model",
        }),
      },
    );
    const result = await svc.autoSplit("p", "doc-1", "u");
    expect(result).toHaveLength(1);
    expect(result[0]!.title).toBe("Auth");
    expect(tx.requirementModule.deleteMany).toHaveBeenCalledWith({ where: { documentId: "doc-1" } });
  });

  it("updateModules rejects empty list and duplicate orders", async () => {
    const svc = makeService({
      requirementDocument: { findFirst: vi.fn().mockResolvedValue({ id: "doc-1" }) },
    });
    await expect(
      svc.updateModules("p", "doc-1", "u", { modules: [] }),
    ).rejects.toBeInstanceOf(BadRequestException);
    await expect(
      svc.updateModules("p", "doc-1", "u", {
        modules: [
          { title: "A", content: "x", order: 1 },
          { title: "B", content: "y", order: 1 },
        ],
      }),
    ).rejects.toBeInstanceOf(BadRequestException);
  });

  it("promoteToRequirement creates a draft requirement", async () => {
    const created = {
      id: "req-1",
      projectId: "p",
      title: "Auth",
      content: "Login",
      status: "draft",
      version: 1,
      createdBy: "u",
      reviewedBy: null,
      approvedBy: null,
      rejectedBy: null,
      archivedBy: null,
      createdAt: new Date(),
      updatedAt: new Date(),
      versions: [],
      events: [],
    };
    const tx = {
      requirement: { create: vi.fn().mockResolvedValue({ id: "req-1" }), findUniqueOrThrow: vi.fn().mockResolvedValue(created) },
      requirementVersion: { create: vi.fn() },
      requirementReviewEvent: { create: vi.fn() },
    };
    const svc = makeService({
      requirementModule: { findFirst: vi.fn().mockResolvedValue({ id: "mod-1", documentId: "doc-1", projectId: "p", title: "Auth", content: "Login" }) },
      $transaction: (cb: (tx: typeof tx) => unknown) => cb(tx),
    });
    const dto = await svc.promoteToRequirement("p", "mod-1", "u");
    expect(dto.status).toBe("draft");
    expect(dto.title).toBe("Auth");
    expect(tx.requirement.create).toHaveBeenCalled();
  });

  it("promoteToRequirement 404 when module missing", async () => {
    const svc = makeService({
      requirementModule: { findFirst: vi.fn().mockResolvedValue(null) },
    });
    await expect(svc.promoteToRequirement("p", "mod-x", "u")).rejects.toBeInstanceOf(NotFoundException);
  });
});
