import { BadRequestException, Injectable, NotFoundException } from "@nestjs/common";
import { PrismaService } from "../../infra/prisma/prisma.service";
import { AuditService } from "../audit/audit.service";
import { LlmDraftService } from "../ai-orchestration/llm-draft.service";
import type {
  RequirementDto,
  RequirementModuleDto,
  RequirementStatus,
  UpdateRequirementModulesRequest,
} from "@crab/shared-types";

const MODULE_STATUSES = new Set<RequirementStatus>(["draft", "in-review", "approved", "rejected", "archived"]);

interface ModuleRow {
  id: string;
  documentId: string;
  projectId: string;
  order: number;
  title: string;
  content: string;
  confidenceScore: number | null;
  isAutoGenerated: boolean;
  createdAt: Date;
  updatedAt: Date;
}

@Injectable()
export class RequirementModulesService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly audit: AuditService,
    private readonly llmDraft: LlmDraftService,
  ) {}

  async list(projectId: string, docId: string): Promise<RequirementModuleDto[]> {
    await this.ensureDoc(projectId, docId);
    const rows = await this.prisma.requirementModule.findMany({
      where: { documentId: docId, projectId },
      orderBy: { order: "asc" },
    });
    return rows.map((row) => this.toDto(row));
  }

  async autoSplit(
    projectId: string,
    docId: string,
    actorId: string,
    providerId?: string,
  ): Promise<RequirementModuleDto[]> {
    const doc = await this.ensureDoc(projectId, docId);
    if (!doc.parsedText || doc.status !== "extracted") {
      throw new BadRequestException(
        "Document text must be extracted before AI splitting. Re-run extraction first.",
      );
    }

    const split = await this.llmDraft.generateModules(
      providerId,
      doc.parsedText,
      doc.mimeType,
      projectId,
    );

    const modules = await this.prisma.$transaction(async (tx) => {
      await tx.requirementModule.deleteMany({ where: { documentId: docId } });
      await tx.requirementModule.createMany({
        data: split.modules.map((m) => ({
          documentId: docId,
          projectId,
          order: m.order,
          title: m.title,
          content: m.content,
          confidenceScore: m.confidence,
          isAutoGenerated: true,
        })),
      });
      return tx.requirementModule.findMany({
        where: { documentId: docId, projectId },
        orderBy: { order: "asc" },
      });
    });

    await this.audit.record({
      actorId,
      projectId,
      action: "requirement-module.split",
      targetType: "requirement-document",
      targetId: docId,
      outcome: "success",
      metadata: { count: modules.length, model: split.modelUsed },
    });

    return modules.map((row) => this.toDto(row as unknown as ModuleRow));
  }

  async updateModules(
    projectId: string,
    docId: string,
    actorId: string,
    req: UpdateRequirementModulesRequest,
  ): Promise<RequirementModuleDto[]> {
    if (!req.modules.length) {
      throw new BadRequestException("Modules list cannot be empty");
    }
    if (new Set(req.modules.map((m) => m.order)).size !== req.modules.length) {
      throw new BadRequestException("Duplicate module order values");
    }
    await this.ensureDoc(projectId, docId);

    const modules = await this.prisma.$transaction(async (tx) => {
      await tx.requirementModule.deleteMany({ where: { documentId: docId } });
      await tx.requirementModule.createMany({
        data: req.modules.map((m) => ({
          documentId: docId,
          projectId,
          order: m.order,
          title: m.title,
          content: m.content,
          confidenceScore: null,
          isAutoGenerated: false,
        })),
      });
      return tx.requirementModule.findMany({
        where: { documentId: docId, projectId },
        orderBy: { order: "asc" },
      });
    });

    await this.audit.record({
      actorId,
      projectId,
      action: "requirement-module.update",
      targetType: "requirement-document",
      targetId: docId,
      outcome: "success",
      metadata: { count: modules.length },
    });

    return modules.map((row) => this.toDto(row as unknown as ModuleRow));
  }

  /**
   * Promote a module to a real Requirement in draft status. The module content
   * becomes the first version of the requirement. The module row is preserved
   * so the audit trail back to the source document remains intact.
   */
  async promoteToRequirement(
    projectId: string,
    moduleId: string,
    actorId: string,
  ): Promise<RequirementDto> {
    const module = await this.prisma.requirementModule.findFirst({
      where: { id: moduleId, projectId },
    });
    if (!module) throw new NotFoundException("Requirement module not found");

    const created = await this.prisma.$transaction(async (tx) => {
      const requirement = await tx.requirement.create({
        data: {
          projectId,
          title: module.title,
          content: module.content,
          status: "draft",
          version: 1,
          createdBy: actorId,
        },
      });
      await tx.requirementVersion.create({
        data: {
          requirementId: requirement.id,
          projectId,
          version: 1,
          title: module.title,
          content: module.content,
          status: "draft",
          createdBy: actorId,
        },
      });
      await tx.requirementReviewEvent.create({
        data: {
          requirementId: requirement.id,
          projectId,
          fromStatus: null,
          toStatus: "draft",
          action: "create",
          actorId,
        },
      });
      return tx.requirement.findUniqueOrThrow({
        where: { id: requirement.id },
        include: {
          versions: { orderBy: { version: "desc" as const } },
          events: { orderBy: { createdAt: "desc" as const } },
        },
      });
    });

    await this.audit.record({
      actorId,
      projectId,
      action: "requirement-module.promote",
      targetType: "requirement",
      targetId: created.id,
      outcome: "success",
      metadata: { moduleId, sourceDocumentId: module.documentId },
    });

    return this.toRequirementDto(created);
  }

  private async ensureDoc(projectId: string, docId: string) {
    const doc = await this.prisma.requirementDocument.findFirst({
      where: { id: docId, projectId },
    });
    if (!doc) throw new NotFoundException("Requirement document not found");
    return doc;
  }

  private toDto(row: ModuleRow): RequirementModuleDto {
    return {
      id: row.id,
      documentId: row.documentId,
      projectId: row.projectId,
      order: row.order,
      title: row.title,
      content: row.content,
      ...(row.confidenceScore !== null ? { confidenceScore: row.confidenceScore } : {}),
      isAutoGenerated: row.isAutoGenerated,
      createdAt: row.createdAt.toISOString(),
      updatedAt: row.updatedAt.toISOString(),
    };
  }

  private toRequirementDto(row: {
    id: string;
    projectId: string;
    title: string;
    content: string;
    status: string;
    version: number;
    createdBy: string;
    reviewedBy: string | null;
    approvedBy: string | null;
    rejectedBy: string | null;
    archivedBy: string | null;
    createdAt: Date;
    updatedAt: Date;
    versions: Array<{
      id: string;
      requirementId: string;
      projectId: string;
      version: number;
      title: string;
      content: string;
      status: string;
      createdBy: string;
      reviewedAt: Date | null;
      approvedAt: Date | null;
      approvedBy: string | null;
      rejectedAt: Date | null;
      rejectedBy: string | null;
      archivedAt: Date | null;
      archivedBy: string | null;
      createdAt: Date;
    }>;
    events: Array<{
      id: string;
      requirementId: string;
      projectId: string;
      fromStatus: string | null;
      toStatus: string;
      action: string;
      actorId: string;
      createdAt: Date;
    }>;
  }): RequirementDto {
    return {
      id: row.id,
      projectId: row.projectId,
      title: row.title,
      content: row.content,
      status: MODULE_STATUSES.has(row.status as RequirementStatus)
        ? (row.status as RequirementStatus)
        : "draft",
      version: row.version,
      createdBy: row.createdBy,
      ...(row.reviewedBy ? { reviewedBy: row.reviewedBy } : {}),
      ...(row.approvedBy ? { approvedBy: row.approvedBy } : {}),
      ...(row.rejectedBy ? { rejectedBy: row.rejectedBy } : {}),
      ...(row.archivedBy ? { archivedBy: row.archivedBy } : {}),
      createdAt: row.createdAt.toISOString(),
      updatedAt: row.updatedAt.toISOString(),
      versions: row.versions.map((v) => ({
        id: v.id,
        requirementId: v.requirementId,
        projectId: v.projectId,
        version: v.version,
        title: v.title,
        content: v.content,
        status: MODULE_STATUSES.has(v.status as RequirementStatus)
          ? (v.status as RequirementStatus)
          : "draft",
        createdBy: v.createdBy,
        ...(v.reviewedAt ? { reviewedAt: v.reviewedAt.toISOString() } : {}),
        ...(v.approvedAt ? { approvedAt: v.approvedAt.toISOString() } : {}),
        ...(v.approvedBy ? { approvedBy: v.approvedBy } : {}),
        ...(v.rejectedAt ? { rejectedAt: v.rejectedAt.toISOString() } : {}),
        ...(v.rejectedBy ? { rejectedBy: v.rejectedBy } : {}),
        ...(v.archivedAt ? { archivedAt: v.archivedAt.toISOString() } : {}),
        ...(v.archivedBy ? { archivedBy: v.archivedBy } : {}),
        createdAt: v.createdAt.toISOString(),
      })),
      reviewEvents: row.events.map((e) => ({
        id: e.id,
        requirementId: e.requirementId,
        projectId: e.projectId,
        ...(e.fromStatus ? { fromStatus: e.fromStatus as RequirementStatus } : {}),
        toStatus: MODULE_STATUSES.has(e.toStatus as RequirementStatus)
          ? (e.toStatus as RequirementStatus)
          : "draft",
        action: e.action as RequirementDto["reviewEvents"][number]["action"],
        actorId: e.actorId,
        createdAt: e.createdAt.toISOString(),
      })),
    };
  }
}
